name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PERSONAL_ACCESS_TOKEN required when storing signatures in another repository
          # PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'document-processor/cla.json'
          path-to-document: 'https://github.com/build-on-ai/document-processor/blob/main/CLA.md'
          branch: 'main'
          allowlist: tmaloziec,bot*
          remote-organization-name: 'build-on-ai'
          remote-repository-name: 'cla-signatures'

          # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          create-file-commit-message: 'For CLA Assistant: Creating file for storing CLA Signatures'
          signed-commit-message: 'For CLA Assistant: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          custom-notsigned-prl-comment: 'Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://github.com/build-on-ai/document-processor/blob/main/CLA.md) before we can accept your contribution. You can sign by posting a comment on this PR using the following: **"I have read the CLA Document and I hereby sign the CLA"**'
          custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          custom-allsigned-prl-comment: 'All contributors have signed the CLA ✓'
